package main

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// styleOf 对单个文件跑 findStyleViolations，解析失败直接终止用例。
func styleOf(t *testing.T, name, src string, opts styleOptions) []string {
	t.Helper()
	got, err := findStyleViolations(name, []byte(src), opts)
	if err != nil {
		t.Fatalf("%s 解析失败：%v", name, err)
	}
	t.Logf("%s → %v", name, got)
	return got
}

// assertPrefixes 断言违规与 want 一一对应，且每条以对应前缀开头。
func assertPrefixes(t *testing.T, got, want []string) {
	t.Helper()
	if len(got) != len(want) {
		t.Fatalf("期望 %d 条违规 %v，得到 %v", len(want), want, got)
	}
	for i, w := range want {
		if !strings.HasPrefix(got[i], w) {
			t.Fatalf("第 %d 条应以 %q 开头，得到 %q", i, w, got[i])
		}
	}
}

func TestFindStyleViolations_加锁后须紧跟同接收者defer解锁(t *testing.T) {
	src := `package p
import "sync"
type S struct{ mu sync.RWMutex; n int }
func (s *S) ok() { s.mu.Lock(); defer s.mu.Unlock(); s.n++ }
func (s *S) okR() int { s.mu.RLock(); defer s.mu.RUnlock(); return s.n }
func (s *S) bad() { s.mu.Lock(); s.n++; s.mu.Unlock() }
func (s *S) mismatch() { s.mu.RLock(); defer s.mu.Unlock() }
func (s *S) other(o *S) { s.mu.Lock(); defer o.mu.Unlock() }
func (s *S) inCase(x int) { switch x { case 1: s.mu.Lock(); s.n++ } }
func (s *S) last() { s.mu.Lock() }
func (s *S) closure() int { return func() int { s.mu.Lock(); defer s.mu.Unlock(); return s.n }() }
func (s *S) tryLock() { s.mu.TryLock() }
`
	got := styleOf(t, "p.go", src, styleOptions{})
	assertPrefixes(t, got, []string{
		"p.go:6: lock-defer：s.mu.Lock()",
		"p.go:7: lock-defer：s.mu.RLock()",
		"p.go:8: lock-defer：s.mu.Lock()",
		"p.go:9: lock-defer：s.mu.Lock()",
		"p.go:10: lock-defer：s.mu.Lock()",
	})
}

func TestFindStyleViolations_NewEvent只能在events包级var(t *testing.T) {
	const imp = "import \"github.com/japansms40-web/gohttpkit/logger\"\n"
	cases := []struct {
		name, file, src string
		want            []string
	}{
		{"events.go包级var放行", "pkg/events.go", "package pkg\n" + imp + "var evA = logger.NewEvent(\"a.b\")\n", nil},
		{"events.go函数体内拦", "pkg/events.go", "package pkg\n" + imp + "func f() { _ = logger.NewEvent(\"a.b\") }\n", []string{"pkg/events.go:3: event-decl："}},
		{"其它文件包级var拦", "pkg/a.go", "package pkg\n" + imp + "var evA = logger.NewEvent(\"a.b\")\n", []string{"pkg/a.go:3: event-decl："}},
		{"别名导入同样拦", "pkg/a.go", "package pkg\nimport lg \"github.com/japansms40-web/gohttpkit/logger\"\nvar evA = lg.NewEvent(\"a.b\")\n", []string{"pkg/a.go:3: event-decl："}},
		{"同名但不是kit的logger不管", "pkg/a.go", "package pkg\nimport \"example.com/logger\"\nvar evA = logger.NewEvent(\"a.b\")\n", nil},
	}
	for _, c := range cases {
		t.Run(c.name, func(t *testing.T) {
			assertPrefixes(t, styleOf(t, c.file, c.src, styleOptions{}), c.want)
		})
	}
}

func TestFindStyleViolations_测试文件不检查(t *testing.T) {
	bad := "package p\nimport \"sync\"\nvar mu sync.Mutex\nfunc f() { mu.Lock() }\n"
	if got := styleOf(t, "p_test.go", bad, styleOptions{}); len(got) != 0 {
		t.Fatalf("测试文件不检查，得到 %v", got)
	}
}

func TestFindStyleViolations_生成文件不检查(t *testing.T) {
	bad := "package p\nimport \"sync\"\nvar mu sync.Mutex\nfunc f() { mu.Lock() }\n"
	gen := "// Code generated by x. DO NOT EDIT.\n\n" + bad
	if got := styleOf(t, "p.go", gen, styleOptions{}); len(got) != 0 {
		t.Fatalf("生成文件不检查，得到 %v", got)
	}
}

func TestFindStyleViolations_解析失败返回错误(t *testing.T) {
	if _, err := findStyleViolations("p.go", []byte("package p\nfunc f( {\n"), styleOptions{}); err == nil {
		t.Fatal("语法错误必须返回 error，调用方据此阻断")
	}
}

func TestFindStyleViolations_panic只在Must与init与带指令函数(t *testing.T) {
	src := `package p
var err error
func MustGet() { panic(err) }
func mustOpen() { panic(err) }
func mustard() { panic(err) }
func init() { panic(err) }
func main() { panic(err) }
//agentguard:allow-panic 启动期注册，fail-fast 是契约
func Register() { panic(err) }
//agentguard:allow-panic
func NoReason() { panic(err) }
func Handle() { go func() { panic(err) }() }
var x = func() int { panic(err) }()
`
	got := styleOf(t, "p.go", src, styleOptions{})
	assertPrefixes(t, got, []string{
		"p.go:5: panic-placement",
		"p.go:7: panic-placement",
		"p.go:11: panic-placement",
		"p.go:12: panic-placement",
		"p.go:13: panic-placement",
	})
	mainPkg := "package main\nvar err error\nfunc main() { panic(err) }\n"
	if got := styleOf(t, "cmd/x/main.go", mainPkg, styleOptions{}); len(got) != 0 {
		t.Fatalf("package main 的 main 可以 panic，得到 %v", got)
	}
}

func TestFindStyleViolations_生产代码不硬造根ctx(t *testing.T) {
	src := "package p\nimport \"context\"\nfunc f() { _ = context.Background(); _ = context.TODO() }\n"
	assertPrefixes(t, styleOf(t, "pkg/p.go", src, styleOptions{}), []string{
		"pkg/p.go:3: root-ctx", "pkg/p.go:3: root-ctx",
	})
	alias := "package p\nimport stdctx \"context\"\nfunc f() { _ = stdctx.Background() }\n"
	assertPrefixes(t, styleOf(t, "pkg/p.go", alias, styleOptions{}), []string{"pkg/p.go:3: root-ctx"})
	if got := styleOf(t, "logger/p.go", src, styleOptions{rootCtxAllow: []string{"logger/"}}); len(got) != 0 {
		t.Fatalf("root_ctx_allow 前缀下放行，得到 %v", got)
	}
	mainPkg := "package main\nimport \"context\"\nfunc main() { _ = context.Background() }\n"
	if got := styleOf(t, "cmd/x/main.go", mainPkg, styleOptions{}); len(got) != 0 {
		t.Fatalf("package main 没有上游 ctx，放行，得到 %v", got)
	}
	derived := "package p\nimport \"context\"\nfunc f(ctx context.Context) { _ = context.WithoutCancel(ctx) }\n"
	if got := styleOf(t, "pkg/p.go", derived, styleOptions{}); len(got) != 0 {
		t.Fatalf("从上游 ctx 派生不算硬造，得到 %v", got)
	}
}

func TestFindStyleViolations_有方法的文件不放纯辅助函数(t *testing.T) {
	src := `package p
import "context"
type T struct{}
func (T) M() {}
func newT() T { return T{} }
func NewT() T { return T{} }
func doCall(ctx context.Context) {}
func init() {}
func _() {}
func helper() {}
func newline() {}
`
	on := styleOptions{helperPlacement: true}
	assertPrefixes(t, styleOf(t, "p.go", src, on), []string{
		"p.go:10: helper-placement：纯辅助函数 helper",
		"p.go:11: helper-placement：纯辅助函数 newline",
	})
	if got := styleOf(t, "p.go", src, styleOptions{}); len(got) != 0 {
		t.Fatalf("开关关闭时不检查，得到 %v", got)
	}
	if got := styleOf(t, "common.go", src, on); len(got) != 0 {
		t.Fatalf("common.go 自身不检查，得到 %v", got)
	}
	noMethod := "package p\nfunc helper() {}\n"
	if got := styleOf(t, "q.go", noMethod, on); len(got) != 0 {
		t.Fatalf("没有方法的文件不受约束，得到 %v", got)
	}
	exempt := styleOptions{helperPlacement: true, helperPlacementExempt: []string{"pkg/p.go"}}
	if got := styleOf(t, "pkg/p.go", src, exempt); len(got) != 0 {
		t.Fatalf("helper_placement_exempt 列出的文件放行，得到 %v", got)
	}
	if got := styleOf(t, "pkg/sub/p.go", src, exempt); len(got) != 2 {
		t.Fatalf("放行按完整路径匹配，不按前缀或文件名，得到 %v", got)
	}
}

func TestScanStyle_读HEAD配置开关(t *testing.T) {
	dir := t.TempDir()
	initRepo(t, dir, map[string]string{
		configPath: "style:\n  helper_placement: true\n",
		"pkg/a.go": "package pkg\ntype T struct{}\nfunc (T) M() {}\nfunc helper() {}\n",
	})
	if err := os.WriteFile(filepath.Join(dir, "pkg/b.go"), []byte("package pkg\nimport \"context\"\nvar c = context.TODO()\n"), 0o600); err != nil {
		t.Fatal(err)
	}
	got, err := scanStyle(dir)
	t.Logf("violations=%v err=%v", got, err)
	if err != nil {
		t.Fatal(err)
	}
	assertPrefixes(t, got, []string{"pkg/a.go:4: helper-placement", "pkg/b.go:3: root-ctx"})
}

func TestScanStyle_跳过测试文件与testdata(t *testing.T) {
	dir := t.TempDir()
	bad := "package pkg\nimport \"sync\"\nvar mu sync.Mutex\nfunc g() { mu.Lock() }\n"
	initRepo(t, dir, map[string]string{
		"pkg/a_test.go":     bad,
		"pkg/testdata/x.go": bad,
	})
	got, err := scanStyle(dir)
	t.Logf("violations=%v err=%v", got, err)
	if err != nil {
		t.Fatal(err)
	}
	if len(got) != 0 {
		t.Fatalf("测试文件与 testdata 不检查，得到 %v", got)
	}
}

func TestScanStyle_配置非法返回错误(t *testing.T) {
	dir := t.TempDir()
	initRepo(t, dir, map[string]string{configPath: "style: [\n", "pkg/a.go": "package pkg\n"})
	if _, err := scanStyle(dir); err == nil {
		t.Fatal("HEAD 配置非法必须阻断")
	}
}

func TestScanStyle_违规按行号数值排序(t *testing.T) {
	dir := t.TempDir()
	src := "package pkg\nimport \"sync\"\nvar mu sync.Mutex\n\n\n\n\n" +
		"func a() { mu.Lock() }\n\nfunc b() { mu.Lock() }\n"
	initRepo(t, dir, map[string]string{"pkg/a.go": src})
	got, err := scanStyle(dir)
	t.Logf("violations=%v err=%v", got, err)
	if err != nil {
		t.Fatal(err)
	}
	assertPrefixes(t, got, []string{"pkg/a.go:8: lock-defer", "pkg/a.go:10: lock-defer"})
}

func TestFindStyleViolations_select分支加锁后无defer也报(t *testing.T) {
	src := "package p\nimport \"sync\"\nvar mu sync.Mutex\nvar ch chan int\n" +
		"func f() { select { case <-ch: mu.Lock() } }\n"
	assertPrefixes(t, styleOf(t, "p.go", src, styleOptions{}), []string{"p.go:5: lock-defer"})
}

func TestFindStyleViolations_裸Must函数名放行panic(t *testing.T) {
	src := "package p\nvar err error\nfunc Must() { panic(err) }\nfunc must() { panic(err) }\n"
	if got := styleOf(t, "p.go", src, styleOptions{}); len(got) != 0 {
		t.Fatalf("Must / must 本身放行，得到 %v", got)
	}
}

func TestFindStyleViolations_空白导入不报(t *testing.T) {
	src := "package p\nimport _ \"context\"\nimport _ \"github.com/japansms40-web/gohttpkit/logger\"\nfunc f() { Background(); NewEvent(\"a\") }\n"
	if got := styleOf(t, "pkg/p.go", src, styleOptions{}); len(got) != 0 {
		t.Fatalf("空白导入不引入名字，不报，得到 %v", got)
	}
}

func TestFindStyleViolations_点导入context的Background与TODO也报(t *testing.T) {
	src := "package p\nimport . \"context\"\nfunc f() { _ = Background(); _ = TODO() }\n"
	assertPrefixes(t, styleOf(t, "pkg/p.go", src, styleOptions{}), []string{"pkg/p.go:3: root-ctx", "pkg/p.go:3: root-ctx"})
}

func TestFindStyleViolations_点导入logger的NewEvent也报(t *testing.T) {
	src := "package pkg\nimport . \"github.com/japansms40-web/gohttpkit/logger\"\nvar evA = NewEvent(\"a.b\")\n"
	assertPrefixes(t, styleOf(t, "pkg/a.go", src, styleOptions{}), []string{"pkg/a.go:3: event-decl："})
}

func TestFindStyleViolations_helper的ctx首参认context别名(t *testing.T) {
	on := styleOptions{helperPlacement: true}
	alias := "package p\nimport stdctx \"context\"\ntype T struct{}\nfunc (T) M() {}\nfunc a(ctx stdctx.Context) {}\n"
	if got := styleOf(t, "p.go", alias, on); len(got) != 0 {
		t.Fatalf("别名导入的 Context 首参是端点主实现，得到 %v", got)
	}
	dot := "package p\nimport . \"context\"\ntype T struct{}\nfunc (T) M() {}\nfunc a(ctx Context) {}\n"
	if got := styleOf(t, "p.go", dot, on); len(got) != 0 {
		t.Fatalf("点导入的 Context 首参是端点主实现，得到 %v", got)
	}
}

func TestFindStyleViolations_root_ctx_allow按目录边界匹配(t *testing.T) {
	src := "package p\nimport \"context\"\nfunc f() { _ = context.Background() }\n"
	opts := styleOptions{rootCtxAllow: []string{"log"}}
	assertPrefixes(t, styleOf(t, "login/p.go", src, opts), []string{"login/p.go:3: root-ctx"})
	if got := styleOf(t, "log/p.go", src, opts); len(got) != 0 {
		t.Fatalf("log/ 目录下放行，得到 %v", got)
	}
}

func TestFindStyleViolations_配置路径先规范化(t *testing.T) {
	helper := "package p\ntype T struct{}\nfunc (T) M() {}\nfunc helper() {}\n"
	ex := styleOptions{helperPlacement: true, helperPlacementExempt: []string{"./pkg/p.go"}}
	if got := styleOf(t, "pkg/p.go", helper, ex); len(got) != 0 {
		t.Fatalf("./pkg/p.go 规范化后应放行，得到 %v", got)
	}
	src := "package p\nimport \"context\"\nfunc f() { _ = context.Background() }\n"
	if got := styleOf(t, "logger/p.go", src, styleOptions{rootCtxAllow: []string{"./logger/"}}); len(got) != 0 {
		t.Fatalf("./logger/ 规范化后应放行，得到 %v", got)
	}
}

func TestFindStyleViolations_行号不受line指令影响(t *testing.T) {
	src := "package p\nimport \"sync\"\nvar mu sync.Mutex\n//line x.go:100\nfunc f() { mu.Lock() }\n"
	assertPrefixes(t, styleOf(t, "p.go", src, styleOptions{}), []string{"p.go:5: lock-defer"})
}
